2023-01-13 20:20:26,930 INFO    MainThread:3010 [wandb_setup.py:_flush():68] Configure stats pid to 3010
2023-01-13 20:20:26,930 INFO    MainThread:3010 [wandb_setup.py:_flush():68] Loading settings from /home/dahala/.config/wandb/settings
2023-01-13 20:20:26,930 INFO    MainThread:3010 [wandb_setup.py:_flush():68] Loading settings from /home/dahala/extremevaluelandslides/wandb/settings
2023-01-13 20:20:26,930 INFO    MainThread:3010 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-01-13 20:20:26,930 INFO    MainThread:3010 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-01-13 20:20:26,930 INFO    MainThread:3010 [wandb_init.py:_log_setup():478] Logging user logs to /home/dahala/extremevaluelandslides/wandb/run-20230113_202026-adybffui/logs/debug.log
2023-01-13 20:20:26,930 INFO    MainThread:3010 [wandb_init.py:_log_setup():479] Logging internal logs to /home/dahala/extremevaluelandslides/wandb/run-20230113_202026-adybffui/logs/debug-internal.log
2023-01-13 20:20:26,931 INFO    MainThread:3010 [wandb_init.py:init():518] calling init triggers
2023-01-13 20:20:26,931 INFO    MainThread:3010 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {'bs': 12}
2023-01-13 20:20:26,931 INFO    MainThread:3010 [wandb_init.py:init():537] re-initializing run, found existing run on stack: d0p5htvu
2023-01-13 20:20:26,934 INFO    MainThread:3010 [wandb_run.py:_finish():1844] finishing run dahal/Extreme Value/d0p5htvu
2023-01-13 20:20:26,934 INFO    MainThread:3010 [jupyter.py:save_history():449] not saving jupyter history
2023-01-13 20:20:26,934 INFO    MainThread:3010 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-01-13 20:20:26,934 INFO    MainThread:3010 [wandb_init.py:_jupyter_teardown():410] cleaning up jupyter logic
2023-01-13 20:20:26,934 INFO    MainThread:3010 [wandb_run.py:_atexit_cleanup():2070] got exitcode: 0
2023-01-13 20:20:26,935 INFO    MainThread:3010 [wandb_run.py:_restore():2053] restore
2023-01-13 20:20:26,935 INFO    MainThread:3010 [wandb_run.py:_restore():2059] restore done
2023-01-13 20:20:38,695 INFO    MainThread:3010 [wandb_run.py:_footer_history_summary_info():3427] rendering history
2023-01-13 20:20:38,695 INFO    MainThread:3010 [wandb_run.py:_footer_history_summary_info():3459] rendering summary
2023-01-13 20:20:38,706 INFO    MainThread:3010 [wandb_run.py:_footer_sync_info():3383] logging synced files
2023-01-13 20:20:38,722 INFO    MainThread:3010 [wandb_init.py:init():571] starting backend
2023-01-13 20:20:38,722 INFO    MainThread:3010 [wandb_init.py:init():575] setting up manager
2023-01-13 20:20:38,725 INFO    MainThread:3010 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-01-13 20:20:38,727 INFO    MainThread:3010 [wandb_init.py:init():582] backend started and connected
2023-01-13 20:20:38,759 INFO    MainThread:3010 [wandb_run.py:_label_probe_notebook():1202] probe notebook
2023-01-13 20:20:38,760 INFO    MainThread:3010 [wandb_run.py:_label_probe_notebook():1212] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-01-13 20:20:38,760 INFO    MainThread:3010 [wandb_init.py:init():670] updated telemetry
2023-01-13 20:20:39,283 INFO    MainThread:3010 [wandb_init.py:init():710] communicating run to backend with 60.0 second timeout
2023-01-13 20:20:40,551 INFO    MainThread:3010 [wandb_run.py:_on_init():2121] communicating current version
2023-01-13 20:20:40,889 INFO    MainThread:3010 [wandb_run.py:_on_init():2125] got version response 
2023-01-13 20:20:40,889 INFO    MainThread:3010 [wandb_init.py:init():758] starting run threads in backend
2023-01-13 20:20:48,551 INFO    MainThread:3010 [wandb_run.py:_console_start():2101] atexit reg
2023-01-13 20:20:48,551 INFO    MainThread:3010 [wandb_run.py:_redirect():1959] redirect: SettingsConsole.WRAP_RAW
2023-01-13 20:20:48,551 INFO    MainThread:3010 [wandb_run.py:_redirect():2024] Wrapping output streams.
2023-01-13 20:20:48,551 INFO    MainThread:3010 [wandb_run.py:_redirect():2046] Redirects installed.
2023-01-13 20:20:48,552 INFO    MainThread:3010 [wandb_init.py:init():798] run started, returning control to user process
2023-01-13 20:20:48,556 INFO    MainThread:3010 [wandb_init.py:_resume_backend():400] resuming backend
2023-01-13 20:21:32,790 INFO    MainThread:3010 [wandb_setup.py:_flush():68] Configure stats pid to 3010
2023-01-13 20:21:32,791 INFO    MainThread:3010 [wandb_setup.py:_flush():68] Loading settings from /home/dahala/.config/wandb/settings
2023-01-13 20:21:32,791 INFO    MainThread:3010 [wandb_setup.py:_flush():68] Loading settings from /home/dahala/extremevaluelandslides/wandb/settings
2023-01-13 20:21:32,791 INFO    MainThread:3010 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-01-13 20:21:32,791 INFO    MainThread:3010 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-01-13 20:21:32,791 INFO    MainThread:3010 [wandb_init.py:_log_setup():478] Logging user logs to /home/dahala/extremevaluelandslides/wandb/run-20230113_202132-yz42aj6y/logs/debug.log
2023-01-13 20:21:32,791 INFO    MainThread:3010 [wandb_init.py:_log_setup():479] Logging internal logs to /home/dahala/extremevaluelandslides/wandb/run-20230113_202132-yz42aj6y/logs/debug-internal.log
2023-01-13 20:21:32,791 INFO    MainThread:3010 [wandb_init.py:_jupyter_setup():428] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x2b7bf93d33d0>
2023-01-13 20:21:32,791 INFO    MainThread:3010 [wandb_init.py:init():518] calling init triggers
2023-01-13 20:21:32,792 INFO    MainThread:3010 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {}
2023-01-13 20:21:32,792 INFO    MainThread:3010 [wandb_init.py:init():537] re-initializing run, found existing run on stack: adybffui
2023-01-13 20:21:32,794 INFO    MainThread:3010 [wandb_run.py:_finish():1844] finishing run dahal/Extreme Value/adybffui
2023-01-13 20:21:32,794 INFO    MainThread:3010 [wandb_run.py:_atexit_cleanup():2070] got exitcode: 0
2023-01-13 20:21:32,795 INFO    MainThread:3010 [wandb_run.py:_restore():2053] restore
2023-01-13 20:21:32,795 INFO    MainThread:3010 [wandb_run.py:_restore():2059] restore done
